metadatadeploy/objects/Account.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    <fields>
        
    <fullName>Calculated_TaxId__c</fullName>
        
        
    <formula>IF(
  NOT(ISBLANK( HealthCloudGA__TaxId__c )), HealthCloudGA__TaxId__c,
  IF(
    NOT(ISBLANK( Parent.HealthCloudGA__TaxId__c )), Parent.HealthCloudGA__TaxId__c,
      Parent.Parent.HealthCloudGA__TaxId__c
  )
)</formula>
        
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        
    <label>Calculated_TaxId</label>
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Top_Level_Account_Id__c</fullName>
        
        
    <formula>IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.ParentId)), Parent.Parent.Parent.Parent.ParentId,
IF(NOT(ISBLANK(Parent.Parent.Parent.ParentId)), Parent.Parent.Parent.ParentId,
IF(NOT(ISBLANK(Parent.Parent.ParentId)), Parent.Parent.ParentId,
IF(NOT(ISBLANK(Parent.ParentId)), Parent.ParentId,
IF(NOT(ISBLANK(ParentId)),ParentId,
Id)))))</formula>
        
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        
    <label>Top_Level_Account_Id</label>
        
        
    <type>Text</type>
        
        
</fields>
    <recordTypes>
        
    <fullName>Group</fullName>
        
    <active>true</active>
        
    <label>Group</label>
        
        
        
        
        
        
        
        
        
        
        
        
</recordTypes>
</CustomObject>

metadatadeploy/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        
    <fullName>Success_Advocate__c</fullName>
        
    <defaultValue>false</defaultValue>
        
        
    <label>Success Advocate</label>
        
    <type>Checkbox</type>
        
</fields>
</CustomObject>

metadatadeploy/objects/Contact.object
<CustomObject>
    <fields>
        
    <fullName>IdP_Id__c</fullName>
        
        
    <description>External Id tied to the user&apos;s IdP Account (Okta Id)</description>
        
    <externalId>true</externalId>
        
    <label>IdP Id</label>
        
    <length>255</length>
        
        
        
    <type>Text</type>
        
    <unique>true</unique>
        
</fields>
    <fields>
        
    <fullName>NPI__c</fullName>
        
        
    <label>NPI</label>
        
    <length>10</length>
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Roles__c</fullName>
        
        
    <label>Roles</label>
        
        
        
    <type>MultiselectPicklist</type>
        
    <valueSet>
            
        <restricted>true</restricted>
            
        <valueSetDefinition>
                
                
            <value>
                    
                <fullName>practitioner</fullName>
                    
                    
                <label>practitioner</label>
                    
            </value>
                
            <value>
                    
                <fullName>organization-admin</fullName>
                    
                    
                <label>organization-admin</label>
                    
            </value>
                
            <value>
                    
                <fullName>staff</fullName>
                    
                    
                <label>staff</label>
                    
            </value>
                
            <value>
                    
                <fullName>biller</fullName>
                    
                    
                <label>biller</label>
                    
            </value>
                
            <value>
                    
                <fullName>monitor</fullName>
                    
                    
                <label>monitor</label>
                    
            </value>
                
        </valueSetDefinition>
            
    </valueSet>
        
        
</fields>
    <fields>
        
    <fullName>User_Status__c</fullName>
        
    <description>User&apos;s Okta status, should only be updated via Clover Assistant or Okta</description>
        
        
    <label>User Status</label>
        
        
        
    <type>Picklist</type>
        
    <valueSet>
            
        <valueSetDefinition>
                
                
            <value>
                    
                <fullName>STAGED</fullName>
                    
                    
                <label>STAGED</label>
                    
            </value>
                
            <value>
                    
                <fullName>PROVISIONED</fullName>
                    
                    
                <label>PROVISIONED</label>
                    
            </value>
                
            <value>
                    
                <fullName>ACTIVE</fullName>
                    
                    
                <label>ACTIVE</label>
                    
            </value>
                
            <value>
                    
                <fullName>PASSWORD_EXPIRED</fullName>
                    
                    
                <label>PASSWORD_EXPIRED</label>
                    
            </value>
                
            <value>
                    
                <fullName>LOCKED_OUT</fullName>
                    
                    
                <label>LOCKED_OUT</label>
                    
            </value>
                
            <value>
                    
                <fullName>RECOVERY</fullName>
                    
                    
                <label>RECOVERY</label>
                    
            </value>
                
            <value>
                    
                <fullName>SUSPENDED</fullName>
                    
                    
                <label>SUSPENDED</label>
                    
            </value>
                
            <value>
                    
                <fullName>DEPROVISIONED</fullName>
                    
                    
                <label>DEPROVISIONED</label>
                    
            </value>
                
        </valueSetDefinition>
            
    </valueSet>
        
</fields>
</CustomObject>

force-app/main/default/classes/AccountController.cls
public with sharing class AccountController {

    /**
     * Gets contacts and relevant user information from contacts associated with
     * the given account and recursively up to three levels deep
     * @param accountId - Id of the account to get contacts from all child accounts
     * @return list of contacts
     */
    @AuraEnabled(cacheable=true)
    public static List<Contact> getContactsWithUserInfo(Id accountId) {
        return [
            SELECT
            Id,
            Name,
            FirstName,
            LastName,
            IdP_Id__c,
            User_Status__c,
            NPI__c,
            Roles__c,
            Email
            FROM Contact
            WHERE (AccountId = :accountId 
            OR Account.ParentId = :accountId
            OR Account.Parent.ParentId = :accountId)
            AND RecordType.DeveloperName IN :Consts.CONTACT_USER_RECORD_TYPES
        ];
    }

    /** 
     * Overriding method to allow for safe filtering of contact records
     */
    @AuraEnabled(cacheable=true)
    public static List<Contact> getContactsWithUserInfo(Id accountId, String filterValue) {
        String queryString = 'SELECT ' +
                             'Id, ' +
                             'Name, ' +
                             'FirstName, ' +
                             'LastName, ' +
                             'IdP_Id__c, ' +
                             'User_Status__c, ' +
                             'NPI__c, ' +
                             'Roles__c, ' +
                             'Email ' +
                             'FROM Contact ' +
                             'WHERE (AccountId = \'' + accountId + '\'' +
                             'OR Account.ParentId = \'' + accountId + '\'' +
                             'OR Account.Parent.Parent.Id = \'' + accountId + '\') ' +
                             'AND RecordType.DeveloperName IN (' + '\'' + Consts.CONTACT_PRACTITIONER_RECORD_TYPE + '\',' + '\'' + Consts.CONTACT_STAFF_RECORD_TYPE + '\') ';
        String filter;
        if (filterValue != null) {
            String safeFilterValue = String.escapeSingleQuotes(filterValue);
            filter = 'AND ( Name LIKE \'%' + safeFilterValue + '%\' ' +
                     'OR Email LIKE \'%' + safeFilterValue + '%\' ' +
                     'OR NPI__c LIKE \'%' + safeFilterValue + '%\' )';
        }
        if (filter != null) queryString += filter;
        return Database.query(queryString);
    }

    /**
     * Gets all practice groups for the given account recursively
     * up to three levels deep
     * @param accountId - Id of the account to get practice groups from
     * @return list of related practice groups and contacts associated to it
     */
    @AuraEnabled(cacheable=true)
    public static List<Account> getAllPracticeGroups(Id recordId) {
        Id accountId = getTopLevelAccountId(recordId);
        return [
            SELECT
            Id,
            Name,
            (SELECT Id FROM AccountContactRelations)
            FROM Account
            WHERE Type = :Consts.ACCOUNT_TYPE_PRACTICE_GROUP
            AND (Id = :accountId
            OR ParentId = :accountId
            OR Parent.ParentId = :accountId
            OR Parent.Parent.ParentId = :accountId)
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Account> getChildPracticeGroups(Id recordId) {
        return [
            SELECT
            Id,
            Name,
            (SELECT Id FROM AccountContactRelations)
            FROM Account
            WHERE Type = :Consts.ACCOUNT_TYPE_PRACTICE_GROUP
            AND (Id = :recordId
            OR ParentId = :recordId
            OR Parent.ParentId = :recordId
            OR Parent.Parent.ParentId = :recordId)
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<AccountContactRelation> getUsersForPracticeGroup(Id accountId) {
        return [
            SELECT
            Id,
            AccountId,
            ContactId,
            Contact.Name,
            Contact.Email,
            Contact.NPI__c,
            Contact.Roles__c,
            Contact.User_Status__c,
            Success_Advocate__c
            FROM AccountContactRelation
            WHERE AccountId = :accountId
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Account getPracticeGroupInfo(Id recordId) {
        return [
            SELECT
            Id,
            Name,
            Calculated_TaxId__c,
            Top_Level_Account_Id__c,
            ParentId,
            Parent.Type,
            Parent.ParentId,
            Parent.Parent.Type
            FROM Account
            WHERE Id = :recordId
        ];
    }

    @AuraEnabled
    public static void createAccountContactRelations(String relationsToInsert) {
        List<AccountContactRelation> relations = (List<AccountContactRelation>)JSON.deserialize(relationsToInsert, List<AccountContactRelation>.class);
        insert relations;
    }

    @AuraEnabled
    public static void removeAccountContactRelations(String relationIdsToRemove) {
        // Todo: add logic to prevent removal of the last practice group from contact
        List<Id> deserializedRelationIds = (List<Id>)JSON.deserialize(relationIdsToRemove, List<Id>.class);
        delete [SELECT Id FROM AccountContactRelation WHERE Id IN :deserializedRelationIds];
    }

    public static Id getTopLevelAccountId(Id accountOrContactId) {
        Id topLevelAcctId;
        if (accountOrContactId != null) {
            Schema.SObjectType objType = accountOrContactId.getSobjectType();
            if (objType == SObjectType.Account.getSObjectType()) {
                Account acct = [SELECT Top_Level_Account_Id__c FROM Account WHERE Id = :accountOrContactId];
                topLevelAcctId = acct.Top_Level_Account_Id__c;
    
            } else if (objType == SObjectType.Contact.getSObjectType()) {
                Contact cont = [SELECT Account.Top_Level_Account_Id__c FROM Contact WHERE Id = :accountOrContactId];
                topLevelAcctId = cont.Account.Top_Level_Account_Id__c;
            }
        }
        return topLevelAcctId;
    }

}